/* Generated by Together */

package design;

public class AbstractClass {
    public void templateMethod() {
    }

    public void operation1() {
    }

    public void operation2() {
    }
}
