/* Generated by Together */

package design;

public class Bird {
    protected FlyBehavior flyBehaviour;
    protected SingBehaviour singbehaviour;

    /** Delegates to FlyBehavior. */
    public void setFlyBehavior(FlyBehavior fb) {
        flyBehaviour = fb;
    }

    /** Delegates to SingBehaviour. */
    public void setSingBehavior(SingBehaviour singbehaviour) {
        singbehaviour =  singbehaviour;
    }

    public void doFly() {
        flyBehaviour.fly();
    }

    public void doSing() {
        singbehaviour.sing();
    }
}
