/* Generated by Together */

package design;

import java.util.Vector;
import java.util.Enumeration;
public class ConcreteSubject implements Subject {
    public void attach(Observer observer){
            observersVector.addElement(observer);
        }

    public void detach(Observer observer){
            observersVector.removeElement(observer);
        }

    public void inform(){
            java.util.Enumeration enumeration = observers();
            while (enumeration.hasMoreElements()) {
                ((Observer)enumeration.nextElement()).update();
            }
        }

    public Enumeration observers(){
            return ((java.util.Vector) observersVector.clone()).elements();
        }

    private List observersVector = new java.util.Vector();
}
