/* Generated by Together */

package design;

public class ConcreteObserver implements Observer {
    public void update(){
        // Write your code here
    }

    /**
     * @supplierCardinality 1
     * @label has subject 
     */
    private ConcreteSubject lnkConcreteSubject;
}
