/* Generated by Together */

package design;

public abstract class AbstractTitleInfo
{  
   private String titleName;    
   public final void setTitleName(String titleNameIn) {this.titleName = titleNameIn;}
   public final String getTitleName() {return this.titleName;}    
    
   public abstract void accept(TitleBlurbVisitor titleBlurbVisitor);
}


/* Generated by Together */

public interface Subject {
    void attach(Observer observer);

    void detach(Observer observer);

    void inform();

    /**
     * 
     * @label has observers
     * @clientCardinality 1
     * @supplierCardinality 0..
     * **/
    /*# Observer lnkObserver; */
}


