/* Generated by Together */

package design;

/**
* Execute a database transaction.
*
* <P>Should be applied only to operations involving more than one SQL statement.
*
* @used.By {@link MyUserDAO}, {@link MyUserTheoriesDAO}.
* @author <a href="http://www.javapractices.com/">javapractices.com</a>
*/
public interface Tx {

  /**
  * Execute a database transaction, and return the number of edited records.
  */
  int executeTx() throws DAOException;
  
}