create table node
(
    id bigint(20) NOT NULL auto_increment,
    idno varchar(36),
    createdon datetime,
    modifiedon datetime,
    createdby bigint(20),
    modifiedby bigint(20),
    displayname varchar(255),
    description varchar(2048),
    statusmessage varchar(1024),
    createdirectories boolean,
    source varchar(36),
    receiver varchar(36),
    internalqueueurl varchar(2048),
    backupuri varchar(1000),
    inbound_endpoint_fk bigint(20),
    outbound_endpoint_fk bigint(20),
    router_fk varchar(36)  not null,
    nodestatus_fk bigint(20),
    primary key (id),
    foreign key (router_fk) references router (id),
    foreign key (inbound_endpoint_fk) references endpoint (id),
    foreign key (outbound_endpoint_fk) references endpoint (id),
    foreign KEY (createdby) REFERENCES  user (id),
    foreign KEY (modifiedby) REFERENCES  user (id),
    foreign key (nodestatus_fk) references nodestatus (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;