insert into router (startedon, uptime, name, id) values ('2006-10-13 15:51:53', 100000000, 'ROUTER_TEST', 'routerid_1');
insert into endpoint (id, uri, clazzname, cron, endpoint_type_fk) values ( 1, 'file://temp/in', 'clazzname.ddd.d.d.d.d','* * * * * ', 2);
insert into endpoint (id, uri, clazzname, cron, endpoint_type_fk) values ( 2, 'file://temp/out', 'clazzname.ddd.d.d.d.d','* * * * * ', 1);
insert into node (inbound_endpoint_fk, outbound_endpoint_fk, modifiedon, router_fk, name, id) values (1,2,'2006-10-13 15:51:53', 'routerid_1', 'FILE-TO-FILE1', 'nodeid_1');
insert into node (modifiedon, router_fk, name, id) values ('2006-10-13 15:51:53',  'routerid_1', 'FILE-TO-FTP', 'nodeid_2');
insert into sender (name, id) values ('SENDERNAME1', 'senderid_1');
insert into message (creationtimestamp, sender_fk, node_fk, content, id) values ( NOW(), 'senderid_1', 'nodeid_1', 'A message 1', 'msgid_1');
insert into message (creationtimestamp, sender_fk, node_fk, content, id) values ( NOW(), 'senderid_1', 'nodeid_1', 'A message 2', 'msgid_2');
insert into message (creationtimestamp, sender_fk, node_fk, content, id) values ( NOW(), 'senderid_1', 'nodeid_1', 'A message 3', 'msgid_3');
insert into message (creationtimestamp, sender_fk, node_fk, content, id) values ( NOW(), 'senderid_1', 'nodeid_1', 'A message 4', 'msgid_4');
insert into message (creationtimestamp, sender_fk, node_fk, content, id) values ( NOW(), 'senderid_1', 'nodeid_1', 'A message 5', 'msgid_5');
insert into message (creationtimestamp, sender_fk, node_fk, content, id) values ( NOW(), 'senderid_1', 'nodeid_1', 'A message 6', 'msgid_6');
insert into receiver (id, name ) values ( 'receiverid_1', 'A receiver');
insert into receiver (id, name ) values ( 'receiverid_2', 'A receiver');
insert into receiver_message (receiver_fk , message_fk) values ( 'receiverid_1',  'msgid_1' );
