#!/bin/bash
# This script exist to help when developing the grouter. 
# The purpose is to clean nodes in the grouter folder - 
# backup and out folders.
#
# Atuhor: Georges Polyzois


# List nodes to be cleaned
nodes=(filetest-filetest testnode)

GROUTERHOME=~/tmp/grouter_test_install
backupFolder=backup
outFolder=out
inFolder="in"

echo "Using grouterhome set to :$GROUTERHOME"

#
# Takes two argument, nodename and node's folder to be cleaned
# param1 nodename
# param2 folder
cleanNodeFolder()
{
	echo "Cleaning node: $1 with folder : $2" 
  	if [ -z "$2" ]
  	then
  		echo "You must provide two parameters"
		return 1
  	fi
	    
	rm -r $GROUTERHOME/nodes/$1/$2
	mkdir $GROUTERHOME/nodes/$1/$2
}

# 
# Cleans all nodes listed in array
cleanAll()
{
	echo "Cleaning following nodes: ${nodes[*]}"
	for i in ${nodes[@]}; do
		cleanNodeFolder $i $backupFolder
		cleanNodeFolder $i $outFolder
	done
}

#
# param1 node to clean 
cleanNode()
{
	echo "Cleaning node: $1"
	if [ -z "$1" ]
  	then
  		echo "You must provide node name to clean"
		return 1
  	fi
	cleanNodeFolder $1 $backupFolder
	cleanNodeFolder $1 $outFolder
}

#
# param1 node to archive
archiveNode()
{
	echo "Archiving node: $1"
	if [ -z "$1" ]
  	then
  		echo "You must provide node name to archive"
		return 1
  	fi
  	tar -cf $1.tar $GROUTERHOME/nodes/$1
  	
	#cleanNodeFolder $1 $backupFolder
	#cleanNodeFolder $1 $outFolder
}

case "${1}" in
        node)
                cleanNode $2
                ;;
        archive)
                archiveNode $2
                ;;
        all)
                cleanAll
                ;;
        *)
                echo "Please specify node or all"
                exit 1
                ;;
esac
