#!/bin/bash
# This script exist to help when developing the grouter. 
# The purpose is to clean nodes in the grouter folder - 
# backup and out folders.
#
# It can also be used to create a base folder structure.
#
# Author: Georges Polyzois


# List nodes to be cleaned
nodes=(filetest filtest2 ftptest)

GROUTERHOME=/temp/grouter
backupFolder=backup
outFolder=internal/out
inFolder=internal/in


echo "Using grouterhome set to :$GROUTERHOME"

#
# Create nodes accroding to defined list above
setup()
{
	echo "Seting up a grouter instance " 
  	echo "Creating following nodes: ${nodes[*]}"
  	
  	rm -r $GROUTERHOME
  	mkdir $GROUTERHOME
  	
  	for node in ${nodes[@]}; do
		echo "Creating node= : " $node ;
		mkdir -p $GROUTERHOME/nodes/$node; 
		mkdir -p $GROUTERHOME/nodes/$node/$backupFolder;
		mkdir -p $GROUTERHOME/nodes/$node/$inFolder;
		mkdir -p $GROUTERHOME/nodes/$node/$outFolder;
	done
}

#
# Takes two argument, nodename and node's folder to be cleaned
# param1 nodename
# param2 folder
cleanNodeFolder()
{
	echo "Cleaning node: $1 with folder : $2" 
  	if [ -z "$2" ]
  	then
  		echo "You must provide two parameters"
		return 1
  	fi
	    
	rm -r $GROUTERHOME/nodes/$1/$2
	mkdir $GROUTERHOME/nodes/$1/$2
}

# 
# Cleans all nodes listed in array
cleanAll()
{
	echo "Cleaning following nodes: ${nodes[*]}"
	for i in ${nodes[@]}; do
		cleanNodeFolder $i $backupFolder
		cleanNodeFolder $i $outFolder
	done
}

#
# param1 node to clean 
cleanNode()
{
	echo "Cleaning node: $1"
	if [ -z "$1" ]
  	then
  		echo "You must provide node name to clean"
		return 1
  	fi
	cleanNodeFolder $1 $backupFolder
	cleanNodeFolder $1 $outFolder
}

#
# param1 node to archive
archiveNode()
{
	echo "Archiving node: $1"
	if [ -z "$1" ]
  	then
  		echo "You must provide node name to archive"
		return 1
  	fi
  	tar -cf $1.tar $GROUTERHOME/nodes/$1
  	
	#cleanNodeFolder $1 $backupFolder
	#cleanNodeFolder $1 $outFolder
}

case "${1}" in
        setup)
                setup $2
                ;;
        node)
                cleanNode $2
                ;;
        archive)
                archiveNode $2
                ;;
        all)
                cleanAll
                ;;
        *)
                echo "Please specify [setup cleanNode archiveNode cleanAll]"
                exit 1
                ;;
esac
